# Example .github/workflows/main.yml
name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main # or your main branch name

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Use v4 for the latest version
      - name: Setup Node.js
        uses: actions/setup-node@v4 # Use v4 for the latest version
        with:
          node-version: '18' # Or your desired Node.js version
      - name: Install dependencies
        run: npm install # Or `yarn install`

      # If you have a build step (e.g., for React, Angular, Vue)
      - name: Build project
        run: npm run build # Or `yarn build`

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}' # This is GitHub's built-in token
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TOKEN }}' # <-- Use your new secret here
          projectId: krew-coin-59012 # Your Firebase Project ID
          # channelId: live # Optional: specify a hosting channel (e.g., 'live', 'preview')
          # This assumes your build output is in a `build` directory, change if different
          # public: "build" # Example if your build output is in 'build/' directory
          # entryPoint: "./" # Example if your firebase.json is at the root
